import 'dart:io';
import '../models/note.dart';
import 'midi_generator.dart';
import 'tab_generator.dart';

class ExportService {
  final TabGeneratorService _tabGenerator = TabGeneratorService();

  /// Export notes as MIDI file
  Future<String> exportAsMidi(
    List<Note> notes,
    String fileName, {
    int bpm = 120,
    int instrument = 0,
  }) async {
    final outputPath = await _getExportPath(fileName, 'mid');
    
    await MidiGeneratorService.generateMidiFromNotes(
      notes,
      outputPath,
      bpm: bpm,
      instrument: instrument,
    );
    
    return outputPath;
  }

  /// Export notes as guitar tablature text file
  Future<String> exportAsTab(List<Note> notes, String fileName) async {
    final outputPath = await _getExportPath(fileName, 'txt');
    final tabContent = _tabGenerator.generateTab(notes);
    final textNotation = _tabGenerator.generateTextNotation(notes);
    
    final fullContent = '''
Guitar Tablature
================
Generated by Autotab - ${DateTime.now()}

$tabContent

$textNotation
''';
    
    final file = File(outputPath);
    await file.writeAsString(fullContent);
    
    return outputPath;
  }

  /// Export notes as text notation file
  Future<String> exportAsTextNotation(List<Note> notes, String fileName) async {
    final outputPath = await _getExportPath(fileName, 'txt');
    final textNotation = _tabGenerator.generateTextNotation(notes);
    
    final fullContent = '''
Musical Notation
================
Generated by Autotab - ${DateTime.now()}

$textNotation
''';
    
    final file = File(outputPath);
    await file.writeAsString(fullContent);
    
    return outputPath;
  }

  /// Export transcription text directly
  Future<String> exportTranscriptionText(String transcriptionText, String fileName) async {
    final outputPath = await _getExportPath(fileName, 'txt');
    
    final file = File(outputPath);
    await file.writeAsString(transcriptionText);
    
    return outputPath;
  }

  /// Get platform-specific export path
  Future<String> _getExportPath(String fileName, String extension) async {
    String exportDir;
    
    if (Platform.isWindows) {
      final userProfile = Platform.environment['USERPROFILE'] ?? '.';
      exportDir = '$userProfile\\Documents\\Autotab';
    } else if (Platform.isLinux || Platform.isMacOS) {
      final home = Platform.environment['HOME'] ?? '.';
      exportDir = '$home/Documents/Autotab';
    } else {
      // For Android/iOS, use temporary directory
      exportDir = Directory.systemTemp.path;
    }
    
    // Create directory if it doesn't exist
    final directory = Directory(exportDir);
    if (!await directory.exists()) {
      await directory.create(recursive: true);
    }
    
    // Generate unique filename with timestamp if file exists
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final baseName = fileName.replaceAll(RegExp(r'[^\w\s-]'), '').trim();
    final safeName = baseName.isEmpty ? 'export' : baseName;
    
    if (Platform.isWindows) {
      return '$exportDir\\${safeName}_$timestamp.$extension';
    } else {
      return '$exportDir/${safeName}_$timestamp.$extension';
    }
  }
}
