import 'dart:io';
import '../models/note.dart';
import 'midi_generator.dart';
import 'tab_generator.dart';

class ExportService {
  final TabGeneratorService _tabGenerator = TabGeneratorService();
  
  /// Map high-level instrument names to General MIDI program numbers.
  /// Values are 0-based, as expected by the MIDI generator.
  static const Map<String, int> _midiProgramByInstrument = {
    'guitar': 24,        // Nylon Guitar
    'electric guitar': 27,
    'bass': 32,          // Acoustic Bass
    'bass guitar': 32,
    'violin': 40,        // Violin
    'banjo': 105,        // Banjo
  };

  /// Resolve a friendly instrument name to a MIDI program number,
  /// defaulting to Acoustic Grand Piano (0) if unknown.
  ///
  /// This is exposed as an instance method so UI code can choose
  /// an appropriate General MIDI program before calling export.
  int resolveMidiProgram(String instrument) {
    if (instrument.isEmpty) return 0;
    final key = instrument.toLowerCase().trim();
    return _midiProgramByInstrument[key] ?? 0;
  }

  /// Export notes as MIDI file
  Future<String> exportAsMidi(
    List<Note> notes,
    String fileName, {
    int? instrument,
    void Function(String message)? log,
  }) async {
    log?.call('Preparing MIDI export for ${notes.length} note(s)...');
    final outputPath = await _getExportPath(fileName, 'mid');
    log?.call('Resolved export path: $outputPath');
    
    final program = instrument ?? 0;

    log?.call('Generating MIDI data (program=$program)...');
    await MidiGeneratorService.generateMidiFromNotes(
      notes,
      outputPath,
      instrument: program,
    );
    log?.call('MIDI file written successfully.');
    
    return outputPath;
  }

  /// Export notes as guitar tablature text file
  Future<String> exportAsTab(
    List<Note> notes,
    String fileName, {
    String instrument = 'guitar',
    void Function(String message)? log,
  }) async {
    log?.call('Preparing tab export for ${notes.length} note(s)...');
    final outputPath = await _getExportPath(fileName, 'txt');
    log?.call('Resolved export path: $outputPath');

    log?.call('Generating tab notation...');
    final tabContent = _tabGenerator.generateTab(notes, instrument: instrument);
    log?.call('Generating text notation...');
    final textNotation = _tabGenerator.generateTextNotation(notes);

    // Format instrument label nicely for the header
    final instrumentLabel = instrument.isEmpty
      ? 'Guitar'
      : instrument[0].toUpperCase() + instrument.substring(1).toLowerCase();
    
    final fullContent = '''
  $instrumentLabel Tablature
  ================
  Generated by Autotab - ${DateTime.now()}

  $tabContent

  $textNotation
  ''';
    
    final file = File(outputPath);
    log?.call('Writing tab file to disk...');
    await file.writeAsString(fullContent);
    log?.call('Tab file written successfully.');
    
    return outputPath;
  }

  /// Export notes as text notation file
  Future<String> exportAsTextNotation(
    List<Note> notes,
    String fileName, {
    void Function(String message)? log,
  }) async {
    log?.call('Preparing text notation export for ${notes.length} note(s)...');
    final outputPath = await _getExportPath(fileName, 'txt');
    log?.call('Resolved export path: $outputPath');

    log?.call('Generating text notation...');
    final textNotation = _tabGenerator.generateTextNotation(notes);
    
    final fullContent = '''
Musical Notation
================
Generated by Autotab - ${DateTime.now()}

$textNotation
''';
    
    final file = File(outputPath);
    log?.call('Writing text notation file to disk...');
    await file.writeAsString(fullContent);
    log?.call('Text notation file written successfully.');
    
    return outputPath;
  }

  /// Export transcription text directly
  Future<String> exportTranscriptionText(
    String transcriptionText,
    String fileName, {
    void Function(String message)? log,
  }) async {
    log?.call('Preparing transcription text export...');
    final outputPath = await _getExportPath(fileName, 'txt');
    log?.call('Resolved export path: $outputPath');
    
    final file = File(outputPath);
    log?.call('Writing transcription text file to disk...');
    await file.writeAsString(transcriptionText);
    log?.call('Transcription text file written successfully.');
    
    return outputPath;
  }

  /// Get the base directory where exports are stored, creating it if needed.
  Future<String> getExportDirectory() async {
    String exportDir;

    if (Platform.isWindows) {
      final userProfile = Platform.environment['USERPROFILE'] ?? '.';
      exportDir = '$userProfile\\Documents\\Autotab';
    } else if (Platform.isLinux || Platform.isMacOS) {
      final home = Platform.environment['HOME'] ?? '.';
      exportDir = '$home/Documents/Autotab';
    } else {
      // For Android/iOS, use temporary directory
      exportDir = Directory.systemTemp.path;
    }

    final directory = Directory(exportDir);
    if (!await directory.exists()) {
      await directory.create(recursive: true);
    }

    return exportDir;
  }

  /// Get platform-specific export path
  Future<String> _getExportPath(String fileName, String extension) async {
    final exportDir = await getExportDirectory();
    
    // Generate unique filename with timestamp if file exists
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final baseName = fileName.replaceAll(RegExp(r'[^\w\s-]'), '').trim();
    final safeName = baseName.isEmpty ? 'export' : baseName;
    
    if (Platform.isWindows) {
      return '$exportDir\\${safeName}_$timestamp.$extension';
    } else {
      return '$exportDir/${safeName}_$timestamp.$extension';
    }
  }
}
